# Welcome to Jekyll!
title: "Piráti Praha 8"
email: praha8@pirati.cz
description: >-
  Česká pirátská strana - místní sdružení Praha 8
keywords: piráti, česká pirátská strana, svoboda, demokracie, pirati na osmičce # dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku

organization:
  name: "Piráti Praha 8"
  email: praha8@pirati.cz
  address: |
      Na Moráni 3,
      120 00 Praha 2
  mapLink: https://mapy.cz/s/norubuzado
  redmineLink: https://redmine.pirati.cz/projects/praha-8
  residenceImg:
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010
  donateLink: https://dary.pirati.cz/podpor-kraj/praha/
  onboardingLink: https://nalodeni.pirati.cz/

contactSummaryItems:
  - type: organizationEmail
  - type: organizationRedmineLink
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
  - type: piratiRootWebsite

calendar:
  id: npabehj0rpaqtgo960ju2vjq2s@group.calendar.google.com
  title: "Kalendář Pirátů Prahy 8"
  page: "https://calendar.google.com/calendar/embed?src=npabehj0rpaqtgo960ju2vjq2s%40group.calendar.google.com&ctz=Europe%2FPrague"

facebook:
  loadSDK: true
  profilePage: "https://www.facebook.com/piratipraha8/"
  profilePageName: "Piráti Praha 8"
  appId: 1526197851008996

forum:
  page: https://forum.pirati.cz/viewforum.php?f=943

youtube:
  channel: UC_zxYLGrkmrYazYt0MzyVlA

twitter:
  loadSDK: true
  profile: piratipraha

instagram:
  profilePage: https://www.instagram.com/pirati.cz/

flicker:
  profilePage: https://www.flickr.com/photos/pirati/

############### SETTINSG #################

theme: jekyll-theme-pirati

sass:
  style: compressed
  sass_dir: _sass
# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 12

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /volby/:path/
  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar: 
        - profile
        - people
  - 
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar: 
         - garant
         - program

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - assets/js
    - assets/img
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-8.4.1/assets/img

styleguide_base_url: 'https://styleguide.pir-test.eu/latest'
